version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config

before_build: nuget restore

environment:
  matrix:
    - project_name: lesson_1.csproj
    - project_name: lesson_2.csproj
    - project_name: lesson_3.csproj

build:
  project: $(project_name)/$(project_name).csproj
  verbosity: minimal

test: off

matrix:
  fast_finish: true

