version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

before_build: nuget restore

build: 
    project: https://github.com/LarisaKarlash/github_lesson/tree/master/lesson_1/lesson_1/lesson_1.csproj
             https://github.com/LarisaKarlash/github_lesson/tree/master/lesson_1/lesson_2/lesson_2.csproj
             https://github.com/LarisaKarlash/github_lesson/tree/master/lesson_1/lesson_3/lesson_3.csproj
    publish_wap: true